title: Treemeliority Market
description: Инструменты и предметы для наблюдения, выращивания, документирования и понимания живых систем.
url: https://market.treemeliority.org
baseurl: ""
lang: ru
markdown: kramdown
permalink: pretty
timezone: Asia/Almaty

defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-sitemap

exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - _site
  - en
  - ru
  - kz
  - _data
  - _includes
  - assets
